# Generated by Django 2.0.4 on 2018-11-25 07:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a_ct_time', models.DateTimeField(auto_created=True)),
                ('a_title', models.CharField(max_length=30)),
                ('a_content', models.TextField()),
                ('a_word_count', models.CharField(blank=True, max_length=10, null=True)),
                ('a_ch_time', models.DateTimeField(auto_now=True)),
                ('a_is_delete', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ImageInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('i_name', models.CharField(default='一张图片', max_length=10)),
                ('i_image', models.CharField(default='null', max_length=30)),
                ('i_is_delete', models.BooleanField(default=False)),
                ('i_article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pmd_article.ArticleInfo')),
            ],
        ),
    ]
